{{- if .Values.zipkin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    name: zipkin
spec:
  type: NodePort
  ports:
  - port: 9411
    targetPort: 9411
    nodePort: 30002
  selector:
    name: zipkin
{{- end -}}
